"""FC Den Bosch / Pro Vercelli — Scouting Report Platform (Streamlit app)."""

import io
import os
import uuid
import time
import base64
from datetime import datetime, timezone, timedelta
import zoneinfo
from pathlib import Path
import streamlit as st
from pptx_utils import (
    TEMPLATES, CLUBS, CLUB_LANGUAGES,
    get_template_config, fill_template, fill_from_bytes,
    check_template_compatibility, extract_competency_descriptions,
)
import storage
from i18n import t, APP_LANGUAGES

# ─── Page config ────────────────────────────────────────────────────────────
st.set_page_config(page_title="Scouting Rapport Pro+", page_icon="", layout="wide")

# (Flag CSS is emitted from _render_flags() — AFTER _apply_theme() — so it
#  can override the theme's global button styles with higher specificity.)

_VIDEO_PREVIEW_LIMIT = 50 * 1024 * 1024

LOGO_DIR = Path(__file__).parent / "Logo's"
_LOGO_DB  = LOGO_DIR / "FC DEN BOSCH LOGO.png"
_LOGO_PV  = LOGO_DIR / "FC_Pro_Vercelli_1892.svg.png"
_LOGO_BFG = LOGO_DIR / "Logo-BFG-White.png"
_LOGO_BFG_B = LOGO_DIR / "Logo-BFG-Black.png"

# Session persistence directory
_SESSION_DIR = Path(__file__).parent / "data" / ".sessions"


def _img_b64(path: Path) -> str:
    if path.exists():
        return base64.b64encode(path.read_bytes()).decode()
    return ""


# ─── Session persistence across browser refresh ────────────────────────────

def _save_session(username: str):
    _SESSION_DIR.mkdir(parents=True, exist_ok=True)
    token = uuid.uuid4().hex
    (_SESSION_DIR / f"{token}.txt").write_text(username, encoding="utf-8")
    st.query_params["s"] = token


def _restore_session() -> str | None:
    token = st.query_params.get("s")
    if token:
        p = _SESSION_DIR / f"{token}.txt"
        if p.exists():
            return p.read_text(encoding="utf-8").strip()
    return None


def _clear_session():
    token = st.query_params.get("s")
    if token:
        p = _SESSION_DIR / f"{token}.txt"
        if p.exists():
            p.unlink(missing_ok=True)
    st.query_params.clear()


# ─── App language helper ────────────────────────────────────────────────────

def _lang() -> str:
    return st.session_state.get("app_lang", "EN")


# ─── Language flag selector (top-left, all pages) ─────────────────────────

_FLAG_DIR = Path(__file__).parent / "Logo's" / "flags"
_FLAGS = {"NL": "nl.png", "EN": "en.png", "IT": "it.png", "ZH": "zh.png"}


def _render_flags():
    """Render language flags as clickable Streamlit buttons that look like ONLY the flag.

    Uses Streamlit's automatic `.st-key-<key>` wrapper class (added in Streamlit
    1.35+) on each button's container, so the CSS selector reliably targets
    the right element in the DOM. The button label is hidden via transparent
    color + hidden inner children; the flag PNG is painted as background-image.

    Clicking a flag triggers st.rerun() — NOT a browser navigation — so
    session_state (club_select, nav_page, player_data, …) is preserved.
    """
    current = _lang()
    _club = st.session_state.get("club_select", "FC Den Bosch")
    accent = "#7a1a1a" if _club == "Pro Vercelli" else "#1a3370"

    css_parts = ["<style>"]
    for code, fname in _FLAGS.items():
        flag_path = _FLAG_DIR / fname
        if not flag_path.exists():
            continue
        b64 = _img_b64(flag_path)
        is_active = code == current
        opacity = "1.0" if is_active else "0.45"
        border = f"3px solid {accent}" if is_active else "2px solid transparent"
        # .st-key-flagbtn_XX is auto-generated by Streamlit for st.button(key="flagbtn_XX")
        css_parts.append(f"""
        .st-key-flagbtn_{code} {{
            display: inline-block !important;
            width: 54px !important;
            max-width: 54px !important;
            flex: 0 0 54px !important;
        }}
        .st-key-flagbtn_{code} button,
        .st-key-flagbtn_{code} div.stButton > button,
        .st-key-flagbtn_{code} [data-testid="stButton"] > button {{
            background-image: url("data:image/png;base64,{b64}") !important;
            background-size: cover !important;
            background-position: center !important;
            background-repeat: no-repeat !important;
            background-color: transparent !important;
            color: transparent !important;
            font-size: 0 !important;
            line-height: 0 !important;
            width: 48px !important;
            min-width: 48px !important;
            max-width: 48px !important;
            height: 32px !important;
            min-height: 32px !important;
            padding: 0 !important;
            margin: 0 !important;
            border: {border} !important;
            border-radius: 6px !important;
            box-shadow: none !important;
            opacity: {opacity} !important;
            transition: opacity 0.12s ease, transform 0.12s ease;
            overflow: hidden !important;
        }}
        .st-key-flagbtn_{code} button *,
        .st-key-flagbtn_{code} button p,
        .st-key-flagbtn_{code} button span,
        .st-key-flagbtn_{code} button div {{
            color: transparent !important;
            font-size: 0 !important;
            line-height: 0 !important;
            visibility: hidden !important;
            display: none !important;
        }}
        .st-key-flagbtn_{code} button:hover {{
            opacity: 1.0 !important;
            transform: scale(1.08);
            background-color: transparent !important;
            border-color: {accent} !important;
            color: transparent !important;
        }}
        """)
    css_parts.append("</style>")
    st.markdown("".join(css_parts), unsafe_allow_html=True)

    cols = st.columns([1, 1, 1, 1, 10])
    for idx, (code, _fname) in enumerate(_FLAGS.items()):
        with cols[idx]:
            # Use a non-breaking space as label — Streamlit requires non-empty.
            clicked = st.button("\u00a0", key=f"flagbtn_{code}")
            if clicked and code != current:
                st.session_state["app_lang"] = code
                st.rerun()


# ─── AI text improvement ────────────────────────────────────────────────────

def _get_anthropic_key() -> str | None:
    try:
        key = st.secrets.get("ANTHROPIC_API_KEY", "")
        if key and not key.startswith("#"):
            return key
    except Exception:
        pass
    return os.environ.get("ANTHROPIC_API_KEY") or None


def improve_text(text: str) -> str:
    api_key = _get_anthropic_key()
    if not api_key:
        st.error("No Anthropic API key.")
        return text
    try:
        import anthropic
        client = anthropic.Anthropic(api_key=api_key)
        msg = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=512,
            messages=[{
                "role": "user",
                "content": (
                  "Spelling/Structuur check! "
                  "Geef uitsluitend de verbeterde tekst terug, zonder introductie of uitleg.\n\n"
                    f"Input: {text}\n"
                    "Output:"
                ),
            }],
        )
        return msg.content[0].text.strip()
    except Exception as exc:
        st.error(f"AI improvement failed: {exc}")
        return text



# ─── Authentication ──────────────────────────────────────────────────────────

def _get_all_users() -> dict[str, dict]:
    """Return all users from secrets as {username: {email, ...}}."""
    try:
        return dict(st.secrets.get("users", {}))
    except Exception:
        return {}


def _authenticate(login_input: str, password: str) -> str | None:
    try:
        users = st.secrets.get("users", {})
        user = users.get(login_input)
        if user and user.get("password") == password:
            return login_input
        for uname, udata in users.items():
            if udata.get("email", "").lower() == login_input.lower() and udata.get("password") == password:
                return uname
    except Exception:
        pass
    return None


def _login_page():
    _render_flags()
    L = _lang()
    db_b64 = _img_b64(_LOGO_DB)
    bfg_b64 = _img_b64(_LOGO_BFG_B)
    st.markdown(
        f"""
        <div style="text-align:center; padding: 2rem 0 1rem 0;">
            <img src="data:image/png;base64,{bfg_b64}" width="320" style="margin-bottom: 10px;"/>
            <h1 style="color:#1e3a8a; margin:0; font-size:2rem;">{t('login_title', L)}</h1>
            <p style="color:#6b7280; margin-top:4px; font-size:.95rem;">{t('login_subtitle', L)}</p>
        </div>
        """,
        unsafe_allow_html=True,
    )
    with st.form("login_form"):
        login_input = st.text_input(t("username", L))
        password = st.text_input(t("password", L), type="password")
        submitted = st.form_submit_button(t("log_in", L), type="primary", use_container_width=True)
    if submitted:
        matched_user = _authenticate(login_input, password)
        if matched_user:
            st.session_state["authenticated"] = True
            st.session_state["username"] = matched_user
            _save_session(matched_user)
            st.rerun()
        else:
            st.error(t("invalid_credentials", L))


# ─── Dynamic styling (matching PDF layouts) ─────────────────────────────────

_THEME_BLUE = {
    "bg": "#eef2f9", "sidebar": "#e4ecf7", "content_bg": "#f5f7fb",
    "primary": "#1a3370", "primary_light": "#3b5ba8", "primary_hover": "#15295a",
    "heading": "#1a3370", "text": "#2c3e5a",
    "label": "#1a3370",
    "border": "#b8c9e2", "border_light": "#d1dff0",
    "select_bg": "#1a3370", "select_border": "#1a3370", "select_text": "#ffffff",
    "btn_border": "#1a3370", "btn_text": "#1a3370", "btn_bg": "#ffffff",
    "btn_primary_bg": "#1a3370", "btn_primary_text": "#ffffff",
    "slider": "#1a3370",
    "card_bg": "#ffffff", "card_border": "#b8c9e2",
    "flag_active_bg": "#1a3370", "flag_active_text": "#ffffff",
    "flag_bg": "#ffffff", "flag_text": "#1a3370", "flag_border": "#b8c9e2",
}

_THEME_RED = {
    "bg": "#f9eeed", "sidebar": "#f5e3e2", "content_bg": "#fdf6f5",
    "primary": "#7a1a1a", "primary_light": "#a63030", "primary_hover": "#5a1010",
    "heading": "#7a1a1a", "text": "#4a2020",
    "label": "#7a1a1a",
    "border": "#d4a0a0", "border_light": "#e8c8c8",
    "select_bg": "#7a1a1a", "select_border": "#7a1a1a", "select_text": "#ffffff",
    "btn_border": "#7a1a1a", "btn_text": "#7a1a1a", "btn_bg": "#ffffff",
    "btn_primary_bg": "#7a1a1a", "btn_primary_text": "#ffffff",
    "slider": "#7a1a1a",
    "card_bg": "#ffffff", "card_border": "#d4a0a0",
    "flag_active_bg": "#7a1a1a", "flag_active_text": "#ffffff",
    "flag_bg": "#ffffff", "flag_text": "#7a1a1a", "flag_border": "#d4a0a0",
}


def _apply_theme(club: str) -> None:
    th = _THEME_RED if club == "Pro Vercelli" else _THEME_BLUE
    st.markdown(f"""
    <style>
    /* Page backgrounds */
    [data-testid="stAppViewContainer"] {{ background: {th['content_bg']}; }}
    [data-testid="stHeader"]           {{ background: {th['content_bg']}; }}
    [data-testid="stSidebar"]          {{ background: {th['sidebar']}; }}

    /* Typography */
    h1, h2, h3, h4 {{ color: {th['heading']} !important; }}
    p, li, label, .stMarkdown {{ color: {th['text']} !important; }}

    /* Sidebar labels */
    [data-testid="stSidebar"] label {{ color: {th['label']} !important; font-weight: 600; font-size: 0.85rem; }}

    /* Selectboxes — outlined style matching buttons */
    [data-baseweb="select"] > div {{
        background-color: {th['btn_bg']} !important;
        border: 2px solid {th['btn_border']} !important;
        border-radius: 10px !important;
    }}
    [data-baseweb="select"] * {{ color: {th['btn_text']} !important; font-weight: 600 !important; }}
    [data-baseweb="select"] svg {{ fill: {th['btn_text']} !important; }}
    [data-baseweb="popover"] [role="listbox"] {{ background-color: #ffffff !important; border: 1px solid #cbd5e1 !important; border-radius: 8px !important; }}
    [data-baseweb="popover"] [role="option"] {{ background-color: #ffffff !important; color: #374151 !important; }}
    [data-baseweb="popover"] [role="option"]:hover {{ background-color: {th['bg']} !important; color: {th['heading']} !important; }}

    /* Override Streamlit primary color variable for radio dots */
    :root, [data-testid="stSidebar"] {{
        --primary-color: {th['btn_primary_bg']} !important;
    }}
    /* Radio buttons (navigation) — dots in dark button color */
    [data-testid="stSidebar"] [role="radiogroup"] label {{ color: {th['text']} !important; }}
    [data-testid="stSidebar"] [role="radiogroup"] label p {{ color: {th['text']} !important; }}
    [data-testid="stSidebar"] [role="radio"] > div:first-child {{
        border-color: {th['btn_primary_bg']} !important;
    }}
    [data-testid="stSidebar"] [role="radio"][aria-checked="true"] > div:first-child {{
        background-color: {th['btn_primary_bg']} !important;
        border-color: {th['btn_primary_bg']} !important;
    }}
    [data-testid="stSidebar"] [role="radio"][aria-checked="true"] > div:first-child > div {{
        background-color: {th['btn_primary_bg']} !important;
    }}
    /* Broader selectors for all Streamlit versions */
    [data-testid="stSidebar"] .st-emotion-cache-1gwvy71 {{
        background-color: {th['btn_primary_bg']} !important;
        border-color: {th['btn_primary_bg']} !important;
    }}
    [data-testid="stSidebar"] div[data-testid="stRadio"] label > div:first-child > div {{
        border-color: {th['btn_primary_bg']} !important;
    }}
    [data-testid="stSidebar"] div[data-testid="stRadio"] label[data-checked="true"] > div:first-child > div {{
        background-color: {th['btn_primary_bg']} !important;
    }}

    /* Slider */
    [data-testid="stSlider"] > div > div > div > div {{ background: {th['slider']} !important; }}
    [data-baseweb="slider"] [role="slider"] {{
        width:18px !important; height:18px !important;
        background-color:#ffffff !important; border:3px solid #000000 !important; box-shadow:none !important;
    }}

    /* All buttons — outlined style by default */
    div.stButton > button {{
        background-color: {th['btn_bg']} !important; color: {th['btn_text']} !important;
        border: 2px solid {th['btn_border']} !important;
        font-weight: 600; font-size: 14px; padding: .5rem 1rem; border-radius: 10px;
    }}
    div.stButton > button:hover {{
        background-color: {th['bg']} !important; color: {th['primary']} !important;
    }}
    /* Primary buttons — filled (white text) */
    div.stButton > button[kind="primary"],
    div.stButton > button[kind="primary"] span,
    div.stButton > button[kind="primary"] p,
    [data-testid="stFormSubmitButton"] > button,
    [data-testid="stFormSubmitButton"] > button span,
    [data-testid="stFormSubmitButton"] > button p {{
        background-color: {th['btn_primary_bg']} !important; color: {th['btn_primary_text']} !important;
        border: 2px solid {th['btn_primary_bg']} !important;
    }}
    div.stButton > button[kind="primary"]:hover,
    div.stButton > button[kind="primary"]:hover span,
    div.stButton > button[kind="primary"]:hover p,
    [data-testid="stFormSubmitButton"] > button:hover,
    [data-testid="stFormSubmitButton"] > button:hover span,
    [data-testid="stFormSubmitButton"] > button:hover p {{
        background-color: {th['primary_hover']} !important; color: #ffffff !important;
        border-color: {th['primary_hover']} !important;
    }}

    /* Download buttons — outlined */
    [data-testid="stDownloadButton"] > button {{
        background-color: {th['btn_bg']} !important; color: {th['btn_text']} !important;
        border: 2px solid {th['btn_border']} !important; font-weight: 600 !important; border-radius: 10px !important;
    }}
    [data-testid="stDownloadButton"] > button:hover {{
        background-color: {th['bg']} !important;
    }}

    /* Expanders (competency sections) — same outlined style as buttons */
    [data-testid="stExpander"] {{
        border: 2px solid {th['btn_border']} !important;
        border-radius: 10px !important;
        background: {th['btn_bg']} !important;
    }}
    [data-testid="stExpander"] summary {{
        color: {th['btn_text']} !important;
        font-weight: 600 !important;
    }}
    [data-testid="stExpander"] summary span {{
        color: {th['btn_text']} !important;
    }}
    [data-testid="stExpander"] svg {{
        fill: {th['btn_text']} !important;
    }}

    /* Text inputs and text areas */
    [data-testid="stTextInput"] input, [data-testid="stTextArea"] textarea {{
        border: 1px solid {th['border']} !important;
        border-radius: 10px !important;
    }}
    /* Override Streamlit's "Press Enter to submit form" text */
    [data-testid="InputInstructions"] {{ font-size: 0 !important; }}
    [data-testid="InputInstructions"]::after {{ content: "Press Enter to submit"; font-size: 0.875rem; }}

    /* Dividers */
    hr {{ border-color: {th['border_light']} !important; }}

    /* Star row */
    .var-label {{ font-size:14px; font-weight:700; color:{th['label']}; margin-bottom:2px; letter-spacing:.3px; }}
    .star-row {{ width:60%; display:flex; justify-content:space-between; align-items:center; font-size:26px; line-height:1.2; margin-top:0; margin-bottom:10px; }}
    .star-row span {{ display:inline-block; text-align:center; }}

    /* Report cards */
    .report-card {{
        background: {th['card_bg']}; border: 1px solid {th['card_border']};
        border-radius: 10px; padding: 1rem 1.2rem; margin-bottom: .8rem;
    }}
    .report-card h4 {{ margin: 0 0 4px 0; font-size: 1rem; }}
    .report-card .meta {{ color: #6b7280; font-size: .85rem; }}

    /* Player info card */
    .player-info-card {{
        background: {th['card_bg']}; border: 1px solid {th['card_border']};
        border-radius: 10px; padding: 1.2rem; margin: 0.5rem 0;
    }}
    .player-info-card .info-row {{
        display: flex; padding: 5px 0; border-bottom: 1px solid {th['border_light']};
    }}
    .player-info-card .info-row:last-child {{ border-bottom: none; }}
    /* Small edit button (pencil) aligned bottom-right of cards */
    .edit-btn-small button {{
        background: {th['card_bg']} !important;
        border: 1px solid {th['border_light']} !important;
        color: {th['primary_light']} !important;
        font-size: 0.85rem !important;
        padding: 2px 8px !important;
        min-height: 0 !important;
        border-radius: 6px !important;
        opacity: 0.7;
    }}
    .edit-btn-small button:hover {{
        opacity: 1;
        background: {th['bg']} !important;
    }}
    .edit-btn-small {{ margin-top: -12px; }}
    .player-info-card .info-label {{
        font-weight: 700; color: {th['label']}; min-width: 140px; font-size: 0.9rem;
    }}
    .player-info-card .info-value {{
        color: {th['text']}; font-size: 0.9rem;
    }}

    /* File uploader */
    [data-testid="stFileUploader"] {{
        border: 1px solid {th['border']} !important;
        border-radius: 10px !important;
    }}
    /* Align "Upload video clip" label with the Browse button */
    [data-testid="stFileUploader"] label {{
        padding-left: 1rem !important;
    }}

    /* Competency info tooltip */
    .comp-info-wrap {{
        position: relative;
        display: inline-block;
        margin-left: 6px;
        vertical-align: middle;
        cursor: help;
    }}
    .comp-info-icon {{
        display: inline-flex;
        align-items: center;
        justify-content: center;
        width: 20px;
        height: 20px;
        border-radius: 50%;
        background: {th['primary']};
        color: #ffffff;
        font-size: 12px;
        font-weight: 700;
        font-style: italic;
        font-family: Georgia, serif;
        line-height: 1;
        user-select: none;
    }}
    .comp-info-card {{
        display: none;
        position: absolute;
        left: 28px;
        top: -8px;
        z-index: 9999;
        width: 320px;
        border-radius: 12px;
        overflow: hidden;
        box-shadow: 0 8px 32px rgba(0,0,0,.25);
        font-family: -apple-system, BlinkMacSystemFont, sans-serif;
    }}
    .comp-info-wrap:hover .comp-info-card {{
        display: block;
    }}
    .comp-info-card .ci-header {{
        background: {th['primary']};
        color: #ffffff;
        padding: 14px 18px;
        text-align: center;
    }}
    .comp-info-card .ci-header h4 {{
        margin: 0;
        font-size: 16px;
        font-weight: 800;
        text-transform: uppercase;
        letter-spacing: 1.5px;
        color: #ffffff !important;
    }}
    .comp-info-card .ci-desc {{
        background: {th['primary']};
        color: #ffffffdd;
        padding: 0 18px 14px 18px;
        text-align: center;
        font-size: 13px;
        font-style: italic;
        line-height: 1.4;
    }}
    .comp-info-card .ci-body {{
        background: {th['content_bg']};
        padding: 14px 18px;
    }}
    .comp-info-card .ci-body h5 {{
        margin: 0 0 8px 0;
        font-size: 14px;
        font-weight: 700;
        color: {th['heading']} !important;
    }}
    .comp-info-card .ci-body ul {{
        margin: 0;
        padding: 0 0 0 18px;
    }}
    .comp-info-card .ci-body li {{
        font-size: 13px;
        color: {th['text']} !important;
        line-height: 1.5;
    }}

    </style>
    """, unsafe_allow_html=True)


# ─── Header (matches PDF layout) ────────────────────────────────────────────

def _render_header(club: str, tmpl_lang: str):
    L = _lang()
    logo_b64 = _img_b64(_LOGO_PV if club == "Pro Vercelli" else _LOGO_DB)
    club_color = "#7a1a1a" if club == "Pro Vercelli" else "#1a3370"
    # Map template language code to display name
    lang_display = {"NL": "Nederlands", "ENG": "English"}.get(tmpl_lang, tmpl_lang)
    st.markdown(
        f"""
        <div style="display:flex; align-items:center; gap:14px; padding:0.8rem 0 0.5rem 0;">
            <img src="data:image/png;base64,{logo_b64}" width="65"/>
            <div>
                <h1 style="margin:0; padding:0; font-size:1.6rem; color:{club_color}; letter-spacing:1px; text-transform:uppercase; line-height:1.2;">
                    {t('scout_rating_tool', L)}
                </h1>
                <p style="margin:0; padding:0; color:{club_color}; font-size:.85rem; opacity:.7; line-height:1.2; margin-top:2px;">
                    {club} — {lang_display}
                </p>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


# ─── Shared UI helpers ───────────────────────────────────────────────────────

def _star_row_html(value: float) -> str:
    gold, dark = "#FFD932", "#3a4060"
    full = int(value)
    has_half = (value % 1) >= 0.5
    parts = []
    for i in range(10):
        if i < full:
            parts.append(f'<span style="color:{gold}">★</span>')
        elif i == full and has_half:
            parts.append(
                f'<span style="background:linear-gradient(to right,{gold} 50%,{dark} 50%);'
                f'-webkit-background-clip:text;-webkit-text-fill-color:transparent;'
                f'background-clip:text;color:transparent;">★</span>'
            )
        else:
            parts.append(f'<span style="color:{dark}">★</span>')
    return f'<div class="star-row">{"".join(parts)}</div>'


def star_selector(label: str, key: str, default: float = 0.0) -> float:
    st.markdown(f'<div class="var-label">{label}</div>', unsafe_allow_html=True)
    if key not in st.session_state:
        st.session_state[key] = float(default)
    value: float = st.slider(label, 0.0, 10.0, step=0.5, key=key, label_visibility="collapsed")
    st.markdown(_star_row_html(value), unsafe_allow_html=True)
    return value


def _info_tooltip_html(desc: dict) -> str:
    """Build the HTML for a competency info tooltip card."""
    name = desc.get("name", "")
    description = desc.get("description", "")
    criteria = desc.get("criteria", [])
    if not description and not criteria:
        return ""
    desc_html = f'<div class="ci-desc">&ldquo;{description}&rdquo;</div>' if description else ""
    li_items = "".join(f"<li>{c}</li>" for c in criteria if c and c != "?")
    criteria_html = ""
    if li_items:
        criteria_html = (
            '<div class="ci-body">'
            '<h5>How do we assess this?</h5>'
            f'<ul>{li_items}</ul>'
            '</div>'
        )
    return (
        '<span class="comp-info-wrap">'
        '<span class="comp-info-icon">i</span>'
        '<div class="comp-info-card">'
        f'<div class="ci-header"><h4>{name}</h4></div>'
        f'{desc_html}'
        f'{criteria_html}'
        '</div>'
        '</span>'
    )


def competency_sections(
    variables,
    key_prefix,
    defaults_stars=None,
    defaults_comments=None,
    defaults_videos=None,
    comp_descriptions=None,
    template_name=None,
):
    L = _lang()
    n = len(variables)
    if defaults_stars is None:
        defaults_stars = [0.0] * n
    if defaults_comments is None:
        defaults_comments = [""] * n
    if defaults_videos is None:
        defaults_videos = [None] * n
    if comp_descriptions is None:
        comp_descriptions = []

    star_values, comments, video_data = [], [], []

    # Find the longest variable name so all (i) icons align at the same
    # fixed horizontal position (the user wants them in a neat column).
    longest_label = max(variables, key=len) if variables else ""

    for i, var in enumerate(variables):
        video_key   = f"{key_prefix}_{i}_video"
        comment_key = f"{key_prefix}_{i}_comment"
        # Handle pending accept BEFORE the text_area widget is instantiated
        accept_flag = f"{key_prefix}_{i}_accept_pending"
        if st.session_state.pop(accept_flag, None):
            suggestion_key = f"{key_prefix}_{i}_suggestion"
            st.session_state[comment_key] = st.session_state.get(suggestion_key, "")
            st.session_state[suggestion_key] = ""
        if comment_key not in st.session_state:
            st.session_state[comment_key] = defaults_comments[i] if i < len(defaults_comments) else ""
        if video_key not in st.session_state:
            st.session_state[video_key] = defaults_videos[i] if i < len(defaults_videos) else None

        # Plain label for all profiles (no caps, no emoji)
        display_label = var

        # Show info tooltip if description is available for this competency
        desc = comp_descriptions[i] if i < len(comp_descriptions) else {}
        info_html = _info_tooltip_html(desc)

        if info_html:
            # Create a strictly decreasing z-index so top rows layer over bottom rows
            z_index = 999 - i

            # Use a hidden ruler matching the LONGEST label so all (i)
            # icons line up at the same horizontal position.
            st.markdown(
                f'<div style="position:absolute; z-index:{z_index}; margin-top:13px; display:flex; align-items:center; pointer-events:none;">'
                f'<div style="visibility:hidden; font-family:-apple-system, BlinkMacSystemFont, sans-serif; font-weight:600; font-size:14px; padding-left:46px; white-space:pre; margin:0;">{longest_label}</div>'
                f'<div style="pointer-events:auto; margin-left:8px;">{info_html}</div>'
                f'</div>',
                unsafe_allow_html=True,
            )

        with st.expander(display_label, expanded=False):
            uploaded_video = st.file_uploader(
                t("video_clip", L),
                type=["mp4", "mov", "avi"],
                key=f"{key_prefix}_{i}_uploader",
            )
            if uploaded_video is not None:
                st.session_state[video_key] = (uploaded_video.getvalue(), uploaded_video.name)

            current_video = st.session_state[video_key]
            if current_video is not None:
                vbytes, vname = current_video
                size_mb = len(vbytes) / (1024 * 1024)
                st.caption(f"Video: **{vname}** ({size_mb:.1f} MB)")
                if len(vbytes) <= _VIDEO_PREVIEW_LIMIT:
                    st.video(vbytes)
                else:
                    st.info(t("too_large_preview", L, mb=size_mb))

            st.markdown(f"**{t('rating', L)}:**")
            val = star_selector(var, key=f"{key_prefix}_{i}", default=defaults_stars[i] if i < len(defaults_stars) else 0.0)

            st.text_area(t("scouting_notes", L), key=comment_key, height=90, placeholder="…")

            improve_key    = f"{key_prefix}_{i}_improve"
            suggestion_key = f"{key_prefix}_{i}_suggestion"
            col_btn, _ = st.columns([1, 4])
            with col_btn:
                if st.button(f"✨ {t('improve', L)}", key=improve_key):
                    raw = st.session_state[comment_key]
                    if raw.strip():
                        with st.spinner(f"{t('improving', L)}"):
                            st.session_state[suggestion_key] = improve_text(raw)
                    else:
                        st.warning(t("nothing_to_improve", L))
            if st.session_state.get(suggestion_key):
                suggestion = st.session_state[suggestion_key]
                st.markdown(f"**{t('suggested_improvement', L)}**")
                st.text_area("Suggested", value=suggestion, height=90, key=f"{key_prefix}_{i}_sug_display", label_visibility="collapsed")
                _, col_accept, col_discard, _ = st.columns([1, 1.5, 1.5, 1])
                with col_accept:
                    if st.button(t("accept", L), key=f"{key_prefix}_{i}_accept", type="primary", use_container_width=True):
                        st.session_state[f"{key_prefix}_{i}_accept_pending"] = True
                        st.rerun()
                with col_discard:
                    if st.button(t("discard", L), key=f"{key_prefix}_{i}_discard", use_container_width=True):
                        st.session_state[suggestion_key] = ""
                        st.rerun()

        star_values.append(val)
        comments.append(st.session_state[comment_key])
        video_data.append(st.session_state[video_key])

    return star_values, comments, video_data


_NL_TZ = zoneinfo.ZoneInfo("Europe/Amsterdam")

def _ts_str(ts: float) -> str:
    return datetime.fromtimestamp(ts, tz=_NL_TZ).strftime("%d %b %Y, %H:%M")


def _report_title(meta: dict) -> str:
    player_name = meta.get("player_name") or ""
    if not player_name:
        pd = meta.get("player_data")
        if pd and isinstance(pd, dict):
            player_name = pd.get("name", "")
    pos = meta.get("position", "?")
    return f"{player_name} — {pos}" if player_name else pos


def _current_player_name(state_key: str = "player_data") -> str:
    pd = st.session_state.get(state_key)
    if pd and isinstance(pd, dict):
        return pd.get("name", "")
    return ""


def _pptx_filename(position: str, state_key: str = "player_data") -> str:
    """Build PPTX filename like  14042026 #8 Box to box midfielder Sven Simons.pptx"""
    pd = st.session_state.get(state_key)
    name = ""
    nr = ""
    if pd and isinstance(pd, dict):
        name = pd.get("name", "")
        nr = pd.get("jersey_number", "")
    return _build_pptx_fname(position, name, nr)


def _build_pptx_fname(position: str, player_name: str = "", jersey_nr: str = "") -> str:
    """Build PPTX filename like  14042026 #8 Box to box midfielder Sven Simons.pptx"""
    date_str = datetime.now(_NL_TZ).strftime("%d%m%Y")
    nr_part = f" #{jersey_nr}" if jersey_nr else ""
    role_part = f" {position}" if position else ""
    name_part = f" {player_name}" if player_name else ""
    fname = f"{date_str}{nr_part}{role_part}{name_part}".strip()
    for ch in '<>:"/\\|?*':
        fname = fname.replace(ch, "_")
    return f"{fname}.pptx"


def _collect_editor_state(key_prefix: str, n_vars: int):
    stars, comments, videos = [], [], []
    for i in range(n_vars):
        stars.append(st.session_state.get(f"{key_prefix}_{i}", 0.0))
        comments.append(st.session_state.get(f"{key_prefix}_{i}_comment", ""))
        videos.append(st.session_state.get(f"{key_prefix}_{i}_video"))
    return stars, comments, videos


# ─── Editable player info card ──────────────────────────────────────────────

_PLAYER_FIELDS = [
    ("jersey_number", "jersey_number"),
    ("date_of_birth", "date_of_birth"),
    ("city_of_birth", "city_of_birth"),
    ("nationality", "nationality"),
    ("height", "height"),
    ("preferred_foot", "preferred_foot"),
    ("club_label", "club"),
    ("league", "league"),
    ("agency", "agency"),
    ("agent", "agent"),
]


def _clear_player_card_inputs(key_prefix: str) -> None:
    """Drop cached text_input values for the player card so a newly fetched
    player is not shadowed by the previous player's values.
    """
    st.session_state.pop(f"{key_prefix}_name", None)
    for _, data_key in _PLAYER_FIELDS:
        st.session_state.pop(f"{key_prefix}_{data_key}", None)
    st.session_state.pop(f"{key_prefix}_editing", None)


def _clear_stats_card_inputs(key_prefix: str) -> None:
    """Drop cached number_input values for the stats card."""
    for _, fields in _STATS_FIELDS:
        for _, data_key in fields:
            st.session_state.pop(f"{key_prefix}_{data_key}", None)
    st.session_state.pop(f"{key_prefix}_editing", None)


def _render_player_card(
    pdata: dict,
    editable: bool = True,
    key_prefix: str = "pinfo",
    state_key: str = "player_data",
):
    """Render player info card. If editable=True, shows an edit toggle.

    `state_key` is the session_state slot the "Save info" button writes back
    to (so New Report and Upload & Edit can keep independent player data).
    """
    L = _lang()
    name = pdata.get("name", "")
    st.markdown(f"### {t('player_info', L)}: {name}")

    edit_key = f"{key_prefix}_editing"
    is_editing = st.session_state.get(edit_key, False)

    if editable and is_editing:
        pdata["name"] = st.text_input(
            "Name", value=pdata.get("name", ""), key=f"{key_prefix}_name",
        )
        for label_key, data_key in _PLAYER_FIELDS:
            pdata[data_key] = st.text_input(
                t(label_key, L), value=pdata.get(data_key, ""), key=f"{key_prefix}_{data_key}",
            )
        if st.button(f"💾 {t('save_info', L)}", key=f"{key_prefix}_save", type="primary"):
            st.session_state[state_key] = pdata
            st.session_state[edit_key] = False
            st.rerun()
    else:
        # Read-only display with edit button pinned to bottom-right of card
        rows_html = ""
        for label_key, data_key in _PLAYER_FIELDS:
            value = pdata.get(data_key, "")
            rows_html += f"""
            <div class="info-row">
                <div class="info-label">{t(label_key, L)}</div>
                <div class="info-value">{value or '—'}</div>
            </div>"""

        if editable:
            rows_html += '<div style="display:flex; justify-content:flex-end; padding-top:8px;" id="edit-placeholder-player"></div>'

        st.markdown(f'<div class="player-info-card">{rows_html}</div>', unsafe_allow_html=True)

        if editable:
            # Place st.button right-aligned just below the card (visually overlaps)
            _, edit_col = st.columns([11, 1])
            with edit_col:
                st.markdown('<div class="edit-btn-small" style="margin-top:-30px;">', unsafe_allow_html=True)
                if st.button("✏️", key=f"{key_prefix}_edit", help=t("edit_info", L)):
                    st.session_state[edit_key] = True
                    st.rerun()
                st.markdown('</div>', unsafe_allow_html=True)


# ─── Transfermarkt stats card ──────────────────────────────────────────────

_STATS_FIELDS = [
    ("season_label", [
        ("matches", "season_matches"),
        ("minutes", "season_minutes"),
        ("goals", "season_goals"),
        ("assists", "season_assists"),
    ]),
    ("career_label", [
        ("matches", "career_matches"),
        ("minutes", "career_minutes"),
        ("goals", "career_goals"),
        ("assists", "career_assists"),
    ]),
]


def _render_stats_card(
    stats: dict,
    player_name: str = "",
    editable: bool = True,
    key_prefix: str = "tm_stats",
    state_key: str = "tm_stats",
):
    """Render Transfermarkt player stats card with optional inline editing."""
    L = _lang()
    st.markdown(f"### {t('player_stats_tm', L)}: {player_name}")

    edit_key = f"{key_prefix}_editing"
    is_editing = st.session_state.get(edit_key, False)

    if editable and is_editing:
        for group_label_key, fields in _STATS_FIELDS:
            st.markdown(f"**{t(group_label_key, L)}**")
            cols = st.columns(len(fields))
            for col_idx, (label_key, data_key) in enumerate(fields):
                with cols[col_idx]:
                    stats[data_key] = st.number_input(
                        t(label_key, L),
                        value=int(stats.get(data_key, 0)),
                        min_value=0,
                        key=f"{key_prefix}_{data_key}",
                    )
        if st.button(f"💾 {t('save_info', L)}", key=f"{key_prefix}_save", type="primary"):
            st.session_state[state_key] = stats
            st.session_state[edit_key] = False
            st.rerun()
    else:
        # Read-only display with edit button pinned to bottom-right of card
        rows_html = ""
        for group_label_key, fields in _STATS_FIELDS:
            rows_html += f'<div class="info-row" style="border-bottom:none;padding-bottom:0;"><div class="info-label" style="font-size:0.95rem;">{t(group_label_key, L)}</div></div>'
            for label_key, data_key in fields:
                val = stats.get(data_key, 0)
                rows_html += f"""
                <div class="info-row" style="padding-left:16px;">
                    <div class="info-label">{t(label_key, L)}</div>
                    <div class="info-value">{val}</div>
                </div>"""
        st.markdown(f'<div class="player-info-card">{rows_html}</div>', unsafe_allow_html=True)

        if editable:
            _, edit_col = st.columns([11, 1])
            with edit_col:
                st.markdown('<div class="edit-btn-small" style="margin-top:-30px;">', unsafe_allow_html=True)
                if st.button("✏️", key=f"{key_prefix}_edit", help=t("edit_info", L)):
                    st.session_state[edit_key] = True
                    st.rerun()
                st.markdown('</div>', unsafe_allow_html=True)


def _transfermarkt_section(
    player_name: str,
    player_club: str = "",
    key_prefix: str = "tm",
    state_key: str = "tm_stats",
) -> dict | None:
    """Render Transfermarkt stats fetch button + stats card.
    Reads from / writes to `state_key` in session_state.
    """
    L = _lang()

    if not player_name:
        return st.session_state.get(state_key)

    if st.button(t("fetch_tm_stats", L), type="primary", use_container_width=True, key=f"{key_prefix}_fetch"):
        try:
            from transfermarkt import fetch_player_stats
            with st.spinner(t("fetching_tm", L)):
                stats = fetch_player_stats(player_name, player_club)
            # Clear cached stats-card inputs so the new values are shown
            _clear_stats_card_inputs(f"{key_prefix}_card")
            st.session_state[state_key] = stats
            if not any(stats.get(k, 0) for k in ["season_matches", "career_matches"]):
                st.warning(t("tm_not_found", L))
        except Exception as exc:
            st.error(f"Transfermarkt error: {exc}")

    stats = st.session_state.get(state_key)
    if stats:
        _render_stats_card(
            stats, player_name,
            editable=True, key_prefix=f"{key_prefix}_card", state_key=state_key,
        )

    return st.session_state.get(state_key)


# ─── Player photo section ─────────────────────────────────────────────────

def _player_photo_section(state_key: str = "player_photo") -> tuple[bytes | None, bytes | None]:
    """Upload a player image, crop it circularly, and preview.

    Returns (full_image_bytes, circular_crop_bytes) or (None, None).
    The full image goes on the welcome slide; the circular crop on the rating slide.
    """
    from PIL import Image, ImageDraw

    L = _lang()
    full_key = f"{state_key}_full"
    circ_key = f"{state_key}_circ"

    st.markdown(f"### {t('player_photo', L)}")

    uploaded = st.file_uploader(
        t("upload_photo", L),
        type=["png", "jpg", "jpeg", "webp"],
        key=f"{state_key}_uploader",
    )

    if uploaded is not None:
        img_bytes = uploaded.getvalue()
        img = Image.open(io.BytesIO(img_bytes))

        # Store original for zoom/pan
        if f"{state_key}_orig" not in st.session_state or st.session_state.get(f"{state_key}_fname") != uploaded.name:
            st.session_state[f"{state_key}_orig"] = img_bytes
            st.session_state[f"{state_key}_fname"] = uploaded.name

        w, h = img.size

        col_full, col_crop = st.columns(2)

        # ── Left column: Original image with crop controls ─────────────
        with col_full:
            st.markdown(f"**{t('original_image', L)}**")

            # Placeholder so preview appears above sliders
            full_preview_placeholder = st.empty()

            # Crop sliders (percentage of each edge to trim)
            crop_t = st.slider(t("crop_top", L), 0, 50, 0, key=f"{state_key}_ct")
            crop_b = st.slider(t("crop_bottom", L), 0, 50, 0, key=f"{state_key}_cb")
            crop_l = st.slider(t("crop_left", L), 0, 50, 0, key=f"{state_key}_cl")
            crop_r = st.slider(t("crop_right", L), 0, 50, 0, key=f"{state_key}_cr")

            # Apply crop to original
            ct_px = int(h * crop_t / 100)
            cb_px = int(h * crop_b / 100)
            cl_px = int(w * crop_l / 100)
            cr_px = int(w * crop_r / 100)
            cropped_full = img.crop((cl_px, ct_px, w - cr_px, h - cb_px))

            # Fill placeholder with cropped preview (above the sliders)
            full_preview_buf = io.BytesIO()
            cropped_full.save(full_preview_buf, format="PNG")
            full_preview_placeholder.image(full_preview_buf.getvalue(), width=250)

        # ── Right column: Circular preview ─────────────────────────────
        with col_crop:
            st.markdown(f"**{t('circular_preview', L)}**")

            # Build circular preview from the cropped original.
            # Use a placeholder so the preview image appears ABOVE the sliders.
            preview_placeholder = st.empty()

            cw, ch = cropped_full.size

            # Zoom and position sliders
            zoom = st.slider(
                t("zoom", L), min_value=1.0, max_value=3.0, value=1.0, step=0.1,
                key=f"{state_key}_zoom",
            )
            circ_crop_size = min(cw, ch) / zoom
            max_offset_x = max(0, int((cw - circ_crop_size) / 2))
            max_offset_y = max(0, int((ch - circ_crop_size) / 2))
            # Clamp existing slider values when zoom changes
            ox_key = f"{state_key}_ox"
            oy_key = f"{state_key}_oy"
            if ox_key in st.session_state:
                st.session_state[ox_key] = max(-max_offset_x, min(max_offset_x, st.session_state[ox_key]))
            if oy_key in st.session_state:
                st.session_state[oy_key] = max(-max_offset_y, min(max_offset_y, st.session_state[oy_key]))

            offset_x = st.slider(
                t("horizontal_pos", L), min_value=-max_offset_x, max_value=max_offset_x, value=0,
                key=ox_key,
            ) if max_offset_x > 0 else 0
            offset_y = st.slider(
                t("vertical_pos", L), min_value=-max_offset_y, max_value=max_offset_y, value=0,
                key=oy_key,
            ) if max_offset_y > 0 else 0

            ccx = cw / 2 + offset_x
            ccy = ch / 2 + offset_y
            cl = max(0, int(ccx - circ_crop_size / 2))
            ct = max(0, int(ccy - circ_crop_size / 2))
            cr = min(cw, int(ccx + circ_crop_size / 2))
            cb = min(ch, int(ccy + circ_crop_size / 2))

            circ_square = cropped_full.crop((cl, ct, cr, cb))
            out_size = 400
            circ_square = circ_square.resize((out_size, out_size), Image.LANCZOS)

            # Apply circular mask
            mask = Image.new("L", (out_size, out_size), 0)
            draw = ImageDraw.Draw(mask)
            draw.ellipse((0, 0, out_size - 1, out_size - 1), fill=255)
            preview = Image.new("RGBA", (out_size, out_size), (0, 0, 0, 0))
            preview.paste(circ_square.convert("RGBA"), mask=mask)

            # Fill the placeholder above the sliders with the preview image
            buf = io.BytesIO()
            preview.save(buf, format="PNG")
            preview_placeholder.image(buf.getvalue(), width=200)

            # Always store the current crop results into session state
            circ_buf = io.BytesIO()
            preview.save(circ_buf, format="PNG")
            st.session_state[circ_key] = circ_buf.getvalue()
            full_buf = io.BytesIO()
            _save_img = cropped_full.convert("RGBA") if cropped_full.mode != "RGBA" else cropped_full
            _save_img.save(full_buf, format="PNG")
            st.session_state[full_key] = full_buf.getvalue()

    elif st.session_state.get(full_key):
        # Show previously accepted photos
        st.caption(t("photo_set", L))
        c1, c2 = st.columns(2)
        with c1:
            st.image(st.session_state[full_key], width=150, caption=t("original_image", L))
        with c2:
            if st.session_state.get(circ_key):
                st.image(st.session_state[circ_key], width=150, caption=t("circular_preview", L))

    return st.session_state.get(full_key), st.session_state.get(circ_key)


# ─── SciSports UI section ───────────────────────────────────────────────────

def _scisports_section(
    key_prefix: str = "sci",
    state_key: str = "player_data",
    tm_state_key: str = "tm_stats",
) -> dict | None:
    """Render SciSports player search/select UI.
    Reads from / writes to `state_key` in session_state.
    """
    L = _lang()

    try:
        from scisports import require_secrets, get_token, search_players, fetch_player_data
    except ImportError:
        return st.session_state.get(state_key)

    secrets = require_secrets()
    if not secrets:
        with st.expander(f"⚙️ {t('configure_scisports', L)}", expanded=False):
            st.info(t("scisports_setup_info", L))
            st.code(
                '[scisports]\n'
                'username = "your_username"\n'
                'password = "your_password"\n'
                'client_id = "your_client_id"\n'
                'client_secret = "your_client_secret"\n'
                'scope = "api recruitment performance"',
                language="toml",
            )
        return st.session_state.get(state_key)

    st.subheader(f"{t('search_player', L)}")

    with st.form(f"{key_prefix}_search_form"):
        query = st.text_input(t("search", L), placeholder=t("search_placeholder", L), key=f"{key_prefix}_query")
        search_submitted = st.form_submit_button(t("search", L), use_container_width=True)

    if search_submitted and query.strip():
        with st.spinner(t("connecting_scisports", L)):
            try:
                token = get_token()
                total, options = search_players(token, query)
                st.session_state[f"{key_prefix}_token"] = token
                st.session_state[f"{key_prefix}_options"] = options
            except Exception as exc:
                st.error(f"SciSports error: {exc}")

    options = st.session_state.get(f"{key_prefix}_options", [])
    if options:
        labels = [opt.label() for opt in options]
        selected_idx = st.selectbox(
            t("select_player", L),
            range(len(labels)),
            format_func=lambda i: labels[i],
            key=f"{key_prefix}_selected_idx",
        )

        if st.button(t("obtain_scisports", L), type="primary", use_container_width=True, key=f"{key_prefix}_obtain"):
            chosen = options[selected_idx]
            token = st.session_state.get(f"{key_prefix}_token")
            if not token:
                token = get_token()
            with st.spinner(t("fetching_data", L)):
                try:
                    pdata = fetch_player_data(token, chosen.player_id)
                    # Clear stale form field values from the previously loaded
                    # player so the new player's data actually shows up in the
                    # editable card (Streamlit prefers session_state over
                    # value= on text_input).
                    _clear_player_card_inputs(f"{key_prefix}_card")
                    # A different player means the previously fetched TM stats
                    # are no longer relevant.
                    _clear_stats_card_inputs(f"new_tm_card")
                    st.session_state.pop(tm_state_key, None)
                    st.session_state[state_key] = pdata
                except Exception as exc:
                    st.error(f"Error: {exc}")

    pdata = st.session_state.get(state_key)
    if pdata:
        _render_player_card(
            pdata, editable=True,
            key_prefix=f"{key_prefix}_card", state_key=state_key,
        )

    return st.session_state.get(state_key)


# ══════════════════════════════════════════════════════════════════════════════
# LOGIN GATE — restore session on refresh
# ══════════════════════════════════════════════════════════════════════════════

if not st.session_state.get("authenticated"):
    restored_user = _restore_session()
    if restored_user:
        st.session_state["authenticated"] = True
        st.session_state["username"] = restored_user
    else:
        _login_page()
        st.stop()

username = st.session_state["username"]
L = _lang()

# ── Pre-load draft values BEFORE sidebar widgets render ─────────────────────
# This prevents StreamlitAPIException when "Continue Editing" sets club/lang
# after the selectbox widgets have already been instantiated.
_pending_draft_id = st.session_state.get("edit_draft_id")
if _pending_draft_id and st.session_state.get("_loaded_draft") != _pending_draft_id:
    _pending_draft = storage.load_draft(username, _pending_draft_id)
    if _pending_draft:
        st.session_state["club_select"] = _pending_draft.get("club", "FC Den Bosch")
        st.session_state["lang_select"] = _pending_draft.get("language", "NL")

# Same pre-load for "Continue Editing" on a received report
_pending_recv_id = st.session_state.get("edit_received_id")
if _pending_recv_id and st.session_state.get("_loaded_draft") != f"recv_{_pending_recv_id}":
    _recv_meta = next(
        (m for m in storage.list_received(username) if m.get("report_id") == _pending_recv_id),
        None,
    )
    if _recv_meta:
        st.session_state["club_select"] = _recv_meta.get("club", "FC Den Bosch")
        st.session_state["lang_select"] = _recv_meta.get("language", "NL")

# ══════════════════════════════════════════════════════════════════════════════
# SIDEBAR
# ══════════════════════════════════════════════════════════════════════════════

with st.sidebar:
    st.markdown(f"**{t('logged_in_as', L)}:** {username}")

    # ── Club & template language ─────────────────────────────────────────────
    # Apply deferred club/lang changes (from dashboard "Continue editing")
    _pc = st.session_state.pop("_pending_club", None)
    if _pc:
        st.session_state["club_select"] = _pc
    _pl = st.session_state.pop("_pending_lang", None)
    if _pl:
        st.session_state["lang_select"] = _pl
    club = st.selectbox(t("choose_club", L), CLUBS, key="club_select")
    available_langs = CLUB_LANGUAGES[club]
    lang = st.selectbox(t("choose_template_language", L), available_langs, key="lang_select")

    st.markdown("---")

    # ── Navigation (default = New Report) ────────────────────────────────────
    nav_options = [t("new_report", L), t("dashboard", L), t("upload_edit", L)]
    nav_keys    = ["New Report", "Dashboard", "Upload & Edit"]

    # Handle programmatic navigation override
    nav_override = st.session_state.pop("_nav_override", None)
    if nav_override and nav_override in nav_keys:
        # Set nav_page to the translated label BEFORE the radio widget renders
        target_idx = nav_keys.index(nav_override)
        st.session_state["nav_page"] = nav_options[target_idx]

    # If nav_page holds a stale translated value (from a different language), fix it
    current_nav = st.session_state.get("nav_page")
    if current_nav and current_nav not in nav_options:
        st.session_state["nav_page"] = nav_options[0]

    selected_nav = st.radio(
        "Navigate",
        nav_options,
        key="nav_page",
        label_visibility="collapsed",
    )
    page = nav_keys[nav_options.index(selected_nav)]

    # ── Logout at bottom ─────────────────────────────────────────────────────
    st.markdown("")
    st.markdown("")
    st.markdown("")
    if st.button(f"{t('log_out', L)}", use_container_width=True, key="logout_btn"):
        _clear_session()
        for key in list(st.session_state.keys()):
            del st.session_state[key]
        st.rerun()

_apply_theme(club)
_render_flags()
_render_header(club, lang)


# ══════════════════════════════════════════════════════════════════════════════
# PAGE: Dashboard
# ══════════════════════════════════════════════════════════════════════════════

if page == "Dashboard":
    st.markdown("---")

    # ── Filter by player name ───────────────────────────────────────────────
    filter_query = st.text_input(
        f"🔍 {t('filter_by_player', L)}",
        key="dashboard_filter",
        placeholder="…",
    ).strip().lower()

    def _matches_filter(meta: dict) -> bool:
        if not filter_query:
            return True
        title = _report_title(meta).lower()
        pname = (meta.get("player_name") or "").lower()
        pd = meta.get("player_data") or {}
        if isinstance(pd, dict):
            pname = pname or pd.get("name", "").lower()
        return filter_query in title or filter_query in pname

    # ── Helpers ─────────────────────────────────────────────────────────────
    def _all_stars_assigned(meta: dict) -> bool:
        """True when every competency has a non-zero star value."""
        sv = meta.get("star_values") or []
        return len(sv) > 0 and all(v > 0 for v in sv)

    def _report_actions(meta: dict, prefix: str, load_pptx_fn, delete_fn, edit_mode: str = "draft"):
        """Render the 3 action buttons (Continue editing | Download | Delete).

        edit_mode:
          "draft"    – pure draft, load via edit_draft_id
          "finished" – finished/shared report, re-load PPTX into upload editor
          "received" – received report, load via edit_received_id
        """
        rid = meta["report_id"]
        c1, c2, c3 = st.columns([2, 2, 1])
        with c1:
            btn_key = f"cont_{prefix}_{rid}"
            if st.button(t("continue_editing", L), key=btn_key, type="primary", use_container_width=True):
                if edit_mode == "received":
                    st.session_state["edit_received_id"] = rid
                elif edit_mode == "finished":
                    st.session_state["edit_finished_id"] = rid
                    st.session_state["_edit_finished_meta"] = meta
                    # Defer club/lang change to before widget render (next rerun)
                    st.session_state["_pending_club"] = meta.get("club", "FC Den Bosch")
                    st.session_state["_pending_lang"] = meta.get("language", "NL")
                else:
                    st.session_state["edit_draft_id"] = rid
                st.session_state["_nav_override"] = "Upload & Edit"
                st.session_state.pop("nav_page", None)
                st.session_state.pop("_loaded_draft", None)
                st.rerun()
        with c2:
            pptx_bytes = load_pptx_fn(username, rid)
            if pptx_bytes:
                st.download_button(
                    f"📥  {t('download_pptx', L)}", data=pptx_bytes,
                    file_name=_build_pptx_fname(
                        meta.get("position", ""),
                        meta.get("player_name", ""),
                        (meta.get("player_data") or {}).get("jersey_number", ""),
                    ),
                    mime="application/vnd.openxmlformats-officedocument.presentationml.presentation",
                    key=f"dl_{prefix}_{rid}", use_container_width=True,
                )
        with c3:
            if st.button(t("delete", L), key=f"del_{prefix}_{rid}", use_container_width=True):
                delete_fn(username, rid)
                st.rerun()

    # ── Collect all finished reports and split into categories ──────────────
    all_finished = [f for f in storage.list_finished(username) if _matches_filter(f)]
    shared_finished = [f for f in all_finished if f.get("shared_to")]
    truly_finished = [f for f in all_finished if not f.get("shared_to") and _all_stars_assigned(f)]
    incomplete_finished = [f for f in all_finished if not f.get("shared_to") and not _all_stars_assigned(f)]

    # ── In Progress: drafts + finished reports without all stars ───────────
    st.subheader(f"📝  {t('in_progress', L)}")
    drafts = [d for d in storage.list_drafts(username) if _matches_filter(d)]
    in_progress = drafts + incomplete_finished
    if not in_progress:
        st.caption(t("no_drafts", L))
    else:
        for item in in_progress:
            rid = item["report_id"]
            title = _report_title(item)
            ts_key = "updated_at" if "updated_at" in item else "finished_at"
            ts_label = t("last_saved", L) if "updated_at" in item else t("finished_at", L)
            st.markdown(
                f"""<div class="report-card">
                <h4>{title}</h4>
                <div class="meta">{item.get('club','')} ({item.get('language','')}) · {ts_label}: {_ts_str(item.get(ts_key, 0))}</div>
                </div>""",
                unsafe_allow_html=True,
            )
            if "updated_at" in item and "finished_at" not in item:
                # Pure draft — load from drafts storage
                _report_actions(item, "draft", lambda u, r: (storage.load_draft(u, r) or {}).get("upload_bytes"), storage.delete_draft, edit_mode="draft")
            else:
                # Incomplete finished report
                _report_actions(item, "incfin", storage.load_finished_pptx, storage.delete_finished, edit_mode="finished")

    st.markdown("---")

    # ── Finished Reports: all stars assigned, not shared ───────────────────
    st.subheader(f"✅  {t('finished_reports', L)}")
    if not truly_finished:
        st.caption(t("no_finished", L))
    else:
        for f in truly_finished:
            rid = f["report_id"]
            title = _report_title(f)
            st.markdown(
                f"""<div class="report-card">
                <h4>{title}</h4>
                <div class="meta">{f['club']} ({f['language']}) · {t('finished_at', L)}: {_ts_str(f['finished_at'])}</div>
                </div>""",
                unsafe_allow_html=True,
            )
            _report_actions(f, "fin", storage.load_finished_pptx, storage.delete_finished, edit_mode="finished")

    st.markdown("---")

    # ── Shared Reports: finished reports that were shared ──────────────────
    st.subheader(f"📤  {t('shared_reports', L)}")
    if not shared_finished:
        st.caption(t("no_shared", L))
    else:
        for f in shared_finished:
            rid = f["report_id"]
            title = _report_title(f)
            shared_to_list = ", ".join(f.get("shared_to", []))
            st.markdown(
                f"""<div class="report-card">
                <h4>{title}</h4>
                <div class="meta">{f['club']} ({f['language']}) · {t('shared_with', L)}: {shared_to_list} · {_ts_str(f.get('shared_at', f['finished_at']))}</div>
                </div>""",
                unsafe_allow_html=True,
            )
            _report_actions(f, "shared", storage.load_finished_pptx, storage.delete_finished, edit_mode="finished")

    st.markdown("---")

    # ── Received Reports ──────────────────────────────────────────────────
    st.subheader(f"📨  {t('received_reports', L)}")
    received = [r for r in storage.list_received(username) if _matches_filter(r)]
    if not received:
        st.caption(t("no_received", L))
    else:
        for r in received:
            rid = r["report_id"]
            title = _report_title(r)
            shared_by = r.get("shared_by", "?")
            shared_at = _ts_str(r.get("shared_at", 0))
            st.markdown(
                f"""<div class="report-card">
                <h4>{title}</h4>
                <div class="meta">{r.get('club','')} ({r.get('language','')}) · {t('shared_by', L)}: {shared_by} · {shared_at}</div>
                </div>""",
                unsafe_allow_html=True,
            )
            _report_actions(r, "recv", storage.load_received_pptx, storage.delete_received, edit_mode="received")


# ══════════════════════════════════════════════════════════════════════════════
# PAGE: New Report
# ══════════════════════════════════════════════════════════════════════════════

elif page == "New Report":
    st.markdown("---")

    # New Report uses its OWN player_data / tm_stats slots so it stays
    # independent from whatever draft is loaded in Upload & Edit.
    NEW_PDATA_KEY = "new_player_data"
    NEW_TM_KEY = "new_tm_stats"

    # ── SciSports player search ──────────────────────────────────────────────
    player_data = _scisports_section(
        key_prefix="sci",
        state_key=NEW_PDATA_KEY,
        tm_state_key=NEW_TM_KEY,
    )

    # ── Transfermarkt stats ─────────────────────────────────────────────────
    _pname = (player_data or {}).get("name", "")
    _pclub = (player_data or {}).get("club", "")
    if _pname:
        tm_stats = _transfermarkt_section(
            _pname, _pclub, key_prefix="new_tm", state_key=NEW_TM_KEY,
        )
    else:
        tm_stats = st.session_state.get(NEW_TM_KEY)

    # ── Player photo ──────────────────────────────────────────────────────
    _new_photo_full, _new_photo_circ = _player_photo_section(state_key="new_player_photo")

    st.markdown("---")

    # ── Role selector (pre-select from SciSports, placeholder first) ────────
    template_names = list(TEMPLATES.keys())
    PLACEHOLDER = t("make_a_choice", L)
    role_options = [PLACEHOLDER] + template_names
    # If SciSports provided a template position, pre-select it on first render
    if (
        player_data
        and player_data.get("template_position")
        and "empty_template_select" not in st.session_state
    ):
        sci_position = player_data["template_position"]
        if sci_position in template_names:
            st.session_state["empty_template_select"] = sci_position

    template_name = st.selectbox(t("role_label", L), role_options, key="empty_template_select")

    # Until the user picks a real profile, show a prompt and skip the rest.
    if template_name == PLACEHOLDER:
        st.info(t("select_profile_prompt", L))
        st.stop()

    template_cfg = get_template_config(template_name, club, lang)

    # Reset on club / language / position change
    reset_key = f"{club}|{lang}|{template_name}"
    if st.session_state.get("empty_prev_key") != reset_key:
        for i in range(20):
            st.session_state[f"empty_{i}"]         = 0.0
            st.session_state[f"empty_{i}_video"]   = None
            st.session_state[f"empty_{i}_comment"] = ""
        st.session_state["empty_prev_key"] = reset_key
        st.session_state.pop("active_report_id", None)
        st.session_state.pop("_loaded_draft", None)

    st.markdown("---")
    st.subheader(t("rate_each_competency", L))

    _comp_descs = extract_competency_descriptions(template_cfg)
    star_values, comments, video_data = competency_sections(
        template_cfg["variables"], key_prefix="empty",
        comp_descriptions=_comp_descs,
        template_name=template_name,
    )

    st.markdown("---")

    col_save, col_gen, col_share = st.columns(3)
    with col_save:
        if st.button(f"{t('save_draft', L)}", use_container_width=True):
            s, c, v = _collect_editor_state("empty", len(template_cfg["variables"]))
            # Generate a PPTX snapshot so the draft can be resumed via Upload & Edit
            with st.spinner(t("building_report", L)):
                snapshot = fill_template(
                    template_cfg, s, c, v,
                    player_data=st.session_state.get(NEW_PDATA_KEY),
                    tm_stats=st.session_state.get(NEW_TM_KEY),
                    player_photo=st.session_state.get("new_player_photo_full"),
                    player_photo_circular=st.session_state.get("new_player_photo_circ"),
                )
            snapshot_bytes = snapshot.getvalue()
            rid = storage.save_draft(
                username,
                st.session_state.get("active_report_id"),
                template_name, club, lang, s, c, v,
                source="empty",
                upload_bytes=snapshot_bytes,
                upload_filename=f"Draft_{template_name.replace(' ', '_')}.pptx",
                player_data=st.session_state.get(NEW_PDATA_KEY),
                tm_stats=st.session_state.get(NEW_TM_KEY),
                photo_full=st.session_state.get("new_player_photo_full"),
                photo_circular=st.session_state.get("new_player_photo_circ"),
            )
            st.session_state["active_report_id"] = rid
            st.success(f"{t('draft_saved', L)} (ID: {rid[:8]})")

    with col_gen:
        if st.button(f"{t('generate_pptx', L)}", type="primary", use_container_width=True, key="empty_gen"):
            s, c, v = _collect_editor_state("empty", len(template_cfg["variables"]))
            with st.spinner(t("building_report", L)):
                output = fill_template(
                    template_cfg, s, c, v,
                    player_data=st.session_state.get(NEW_PDATA_KEY),
                    tm_stats=st.session_state.get(NEW_TM_KEY),
                    player_photo=st.session_state.get("new_player_photo_full"),
                    player_photo_circular=st.session_state.get("new_player_photo_circ"),
                )
            pptx_bytes = output.getvalue()

            rid = st.session_state.get("active_report_id") or uuid.uuid4().hex[:12]
            storage.save_finished(username, rid, template_name, club, lang, pptx_bytes,
                                  player_name=_current_player_name(NEW_PDATA_KEY),
                                  player_data=st.session_state.get(NEW_PDATA_KEY),
                                  star_values=s, comments=c, video_data=v,
                                  tm_stats=st.session_state.get(NEW_TM_KEY),
                                  photo_full=st.session_state.get("new_player_photo_full"),
                                  photo_circular=st.session_state.get("new_player_photo_circ"))
            st.session_state.pop("active_report_id", None)

            st.success(t("report_ready", L))
            st.download_button(
                f"📥  {t('download_pptx', L)}", data=pptx_bytes,
                file_name=_pptx_filename(template_name, NEW_PDATA_KEY),
                mime="application/vnd.openxmlformats-officedocument.presentationml.presentation",
                use_container_width=True,
            )

    with col_share:
        if st.button(f"{t('share', L)}", use_container_width=True, key="empty_share"):
            st.session_state["_share_pending"] = "empty"

    # ── Share dialog ────────────────────────────────────────────────────────
    if st.session_state.get("_share_pending") == "empty":
        all_users = _get_all_users()
        other_scouts = [u for u in all_users if u != username]
        if not other_scouts:
            st.warning("No other scouts available.")
            st.session_state.pop("_share_pending", None)
        else:
            sel_scout = st.selectbox(t("select_scout", L), other_scouts, key="empty_share_scout")
            c_send, c_cancel = st.columns(2)
            with c_send:
                if st.button(t("send_report", L), type="primary", use_container_width=True, key="empty_share_send"):
                    s, c, v = _collect_editor_state("empty", len(template_cfg["variables"]))
                    with st.spinner(t("building_report", L)):
                        output = fill_template(
                            template_cfg, s, c, v,
                            player_data=st.session_state.get(NEW_PDATA_KEY),
                            tm_stats=st.session_state.get(NEW_TM_KEY),
                            player_photo=st.session_state.get("new_player_photo_full"),
                            player_photo_circular=st.session_state.get("new_player_photo_circ"),
                        )
                    pptx_bytes = output.getvalue()
                    rid = st.session_state.get("active_report_id") or uuid.uuid4().hex[:12]
                    player = _current_player_name(NEW_PDATA_KEY) or template_name
                    storage.share_report(
                        from_username=username,
                        to_username=sel_scout,
                        report_id=rid,
                        position=template_name,
                        club=club,
                        language=lang,
                        pptx_bytes=pptx_bytes,
                        player_name=_current_player_name(NEW_PDATA_KEY),
                        star_values=s,
                        comments=c,
                        video_data=v,
                        player_data=st.session_state.get(NEW_PDATA_KEY),
                        tm_stats=st.session_state.get(NEW_TM_KEY),
                        photo_full=st.session_state.get("new_player_photo_full"),
                        photo_circular=st.session_state.get("new_player_photo_circ"),
                    )
                    # Also save as finished + mark shared
                    storage.save_finished(username, rid, template_name, club, lang, pptx_bytes,
                                          player_name=_current_player_name(NEW_PDATA_KEY),
                                          player_data=st.session_state.get(NEW_PDATA_KEY),
                                          star_values=s, comments=c, video_data=v,
                                          tm_stats=st.session_state.get(NEW_TM_KEY),
                                          photo_full=st.session_state.get("new_player_photo_full"),
                                          photo_circular=st.session_state.get("new_player_photo_circ"))
                    storage.mark_shared(username, rid, sel_scout)
                    st.session_state.pop("_share_pending", None)
                    # Auto-send notification emails (receiver gets platform link)
                    try:
                        from email_utils import send_share_emails
                        sender_email = all_users.get(username, {}).get("email", "")
                        receiver_email = all_users.get(sel_scout, {}).get("email", "")
                        mail_results = send_share_emails(
                            sender_name=username,
                            sender_email=sender_email,
                            receiver_name=sel_scout,
                            receiver_email=receiver_email,
                            player_name=player,
                        )
                        for side, (ok, err) in mail_results.items():
                            if not ok and err and "no " not in err:
                                st.warning(f"Email to {side} not sent: {err}")
                    except Exception as exc:
                        st.warning(f"Email sending failed: {exc}")
                    st.success(t("report_shared", L).format(name=sel_scout))
            with c_cancel:
                if st.button("Cancel", use_container_width=True, key="empty_share_cancel"):
                    st.session_state.pop("_share_pending", None)
                    st.rerun()


# ══════════════════════════════════════════════════════════════════════════════
# PAGE: Upload & Edit
# ══════════════════════════════════════════════════════════════════════════════

elif page == "Upload & Edit":
    st.markdown("---")

    # Upload & Edit uses its OWN player_data / tm_stats slots so that the
    # player loaded here (from a draft or received report) does NOT leak into
    # a fresh "New Report" session, and vice versa.
    UPLOAD_PDATA_KEY = "upload_player_data"
    UPLOAD_TM_KEY = "upload_tm_stats"

    # ── Auto-load a draft PPTX when coming from "Continue Editing" ───────────
    _edit_draft_id = st.session_state.pop("edit_draft_id", None)
    if _edit_draft_id and st.session_state.get("_loaded_draft") != _edit_draft_id:
        draft = storage.load_draft(username, _edit_draft_id)
        if draft and draft.get("upload_bytes"):
            file_bytes = draft["upload_bytes"]
            with st.spinner(t("checking", L)):
                check_result = check_template_compatibility(io.BytesIO(file_bytes))
            fname = draft.get("upload_filename") or f"Draft_{draft.get('position','report')}.pptx"
            st.session_state["upload_file_key"]     = f"draft_{_edit_draft_id}"
            st.session_state["upload_bytes"]        = file_bytes
            st.session_state["upload_filename"]     = fname
            st.session_state["upload_check_result"] = check_result
            st.session_state["upload_active_report_id"] = _edit_draft_id
            for i, val in enumerate(check_result.get("current_star_values", [])):
                st.session_state[f"upload_{i}"] = float(val)
            for i, cmt in enumerate(check_result.get("current_comments", [])):
                st.session_state[f"upload_{i}_comment"] = cmt or ""
            for i, vid in enumerate(check_result.get("current_videos", [])):
                st.session_state[f"upload_{i}_video"] = vid
            # Restore player data & tm_stats from draft into the
            # upload-specific slots, and clear any stale cached card inputs.
            _clear_player_card_inputs("upload_sci_card")
            _clear_stats_card_inputs("upload_tm_card")
            if draft.get("player_data"):
                st.session_state[UPLOAD_PDATA_KEY] = draft["player_data"]
            else:
                st.session_state.pop(UPLOAD_PDATA_KEY, None)
            if draft.get("tm_stats"):
                st.session_state[UPLOAD_TM_KEY] = draft["tm_stats"]
            else:
                st.session_state.pop(UPLOAD_TM_KEY, None)
            # Restore player photos
            if draft.get("photo_full"):
                st.session_state["upload_player_photo_full"] = draft["photo_full"]
            if draft.get("photo_circular"):
                st.session_state["upload_player_photo_circ"] = draft["photo_circular"]
            st.session_state["_loaded_draft"] = _edit_draft_id

    # ── Auto-load a received report PPTX when coming from "Continue Editing" ─
    _edit_recv_id = st.session_state.pop("edit_received_id", None)
    if _edit_recv_id and st.session_state.get("_loaded_draft") != f"recv_{_edit_recv_id}":
        recv = storage.load_received(username, _edit_recv_id)
        if recv and recv.get("pptx_bytes"):
            recv_bytes = recv["pptx_bytes"]
            with st.spinner(t("checking", L)):
                check_result = check_template_compatibility(io.BytesIO(recv_bytes))
            fname = f"Received_{recv.get('player_name', 'report')}.pptx"
            st.session_state["upload_file_key"]     = f"recv_{_edit_recv_id}"
            st.session_state["upload_bytes"]        = recv_bytes
            st.session_state["upload_filename"]     = fname
            st.session_state["upload_check_result"] = check_result
            # No active_report_id — treat this as a fresh editing session so
            # Save Draft creates a new draft owned by the current user.
            st.session_state.pop("upload_active_report_id", None)

            # Prefer the rich state stored in the share meta (stars, comments,
            # videos) over what's parsed out of the PPTX — the meta has the
            # ORIGINAL uploaded videos, which the PPTX strips.
            recv_stars = recv.get("star_values") or check_result.get("current_star_values", [])
            recv_comments = recv.get("comments") or check_result.get("current_comments", [])
            recv_videos = recv.get("video_data") or check_result.get("current_videos", [])

            for i, val in enumerate(recv_stars):
                st.session_state[f"upload_{i}"] = float(val)
            for i, cmt in enumerate(recv_comments):
                st.session_state[f"upload_{i}_comment"] = cmt or ""
            for i, vid in enumerate(recv_videos):
                st.session_state[f"upload_{i}_video"] = vid

            # Restore rich player/stats data into upload-specific slots
            _clear_player_card_inputs("upload_sci_card")
            _clear_stats_card_inputs("upload_tm_card")
            if recv.get("player_data"):
                st.session_state[UPLOAD_PDATA_KEY] = recv["player_data"]
            elif recv.get("player_name"):
                st.session_state[UPLOAD_PDATA_KEY] = {"name": recv["player_name"]}
            else:
                st.session_state.pop(UPLOAD_PDATA_KEY, None)
            if recv.get("tm_stats"):
                st.session_state[UPLOAD_TM_KEY] = recv["tm_stats"]
            else:
                st.session_state.pop(UPLOAD_TM_KEY, None)
            # Restore player photos
            if recv.get("photo_full"):
                st.session_state["upload_player_photo_full"] = recv["photo_full"]
            if recv.get("photo_circular"):
                st.session_state["upload_player_photo_circ"] = recv["photo_circular"]

            st.session_state["_loaded_draft"] = f"recv_{_edit_recv_id}"

    # ── Auto-load a finished report when coming from "Continue Editing" ──────
    _edit_fin_id = st.session_state.pop("edit_finished_id", None)
    _edit_fin_meta = st.session_state.pop("_edit_finished_meta", None)
    if _edit_fin_id and st.session_state.get("_loaded_draft") != f"fin_{_edit_fin_id}":
        fin = storage.load_finished(username, _edit_fin_id)
        if fin and fin.get("pptx_bytes"):
            fin_bytes = fin["pptx_bytes"]
            with st.spinner(t("checking", L)):
                check_result = check_template_compatibility(io.BytesIO(fin_bytes))
            fname = _build_pptx_fname(
                fin.get("position", ""),
                fin.get("player_name", ""),
            )
            st.session_state["upload_file_key"]     = f"finished_{_edit_fin_id}"
            st.session_state["upload_bytes"]        = fin_bytes
            st.session_state["upload_filename"]     = fname
            st.session_state["upload_check_result"] = check_result
            st.session_state["upload_active_report_id"] = _edit_fin_id

            # Prefer the rich state stored in meta over PPTX-parsed values
            fin_stars = fin.get("star_values") or check_result.get("current_star_values", [])
            fin_comments = fin.get("comments") or check_result.get("current_comments", [])
            fin_videos = fin.get("video_data") or check_result.get("current_videos", [])

            for i, val in enumerate(fin_stars):
                st.session_state[f"upload_{i}"] = float(val)
            for i, cmt in enumerate(fin_comments):
                st.session_state[f"upload_{i}_comment"] = cmt or ""
            for i, vid in enumerate(fin_videos):
                st.session_state[f"upload_{i}_video"] = vid

            # Restore player/stats data
            _clear_player_card_inputs("upload_sci_card")
            _clear_stats_card_inputs("upload_tm_card")
            if fin.get("player_data"):
                st.session_state[UPLOAD_PDATA_KEY] = fin["player_data"]
            else:
                st.session_state.pop(UPLOAD_PDATA_KEY, None)
            if fin.get("tm_stats"):
                st.session_state[UPLOAD_TM_KEY] = fin["tm_stats"]
            else:
                st.session_state.pop(UPLOAD_TM_KEY, None)
            # Restore photos
            if fin.get("photo_full"):
                st.session_state["upload_player_photo_full"] = fin["photo_full"]
            if fin.get("photo_circular"):
                st.session_state["upload_player_photo_circ"] = fin["photo_circular"]

            st.session_state["_loaded_draft"] = f"fin_{_edit_fin_id}"

    st.caption(t("upload_caption", L))

    uploaded = st.file_uploader(t("upload_pptx", L), type=["pptx"], key="upload_widget")

    if uploaded is not None:
        file_key = f"{uploaded.name}_{uploaded.size}"
        if st.session_state.get("upload_file_key") != file_key:
            file_bytes = uploaded.getvalue()
            with st.spinner(t("checking", L)):
                check_result = check_template_compatibility(io.BytesIO(file_bytes))
            st.session_state["upload_file_key"]     = file_key
            st.session_state["upload_bytes"]        = file_bytes
            st.session_state["upload_filename"]     = uploaded.name
            st.session_state["upload_check_result"] = check_result
            for i, val in enumerate(check_result.get("current_star_values", [])):
                st.session_state[f"upload_{i}"] = float(val)
            for i, cmt in enumerate(check_result.get("current_comments", [])):
                st.session_state[f"upload_{i}_comment"] = cmt or ""
            for i, vid in enumerate(check_result.get("current_videos", [])):
                st.session_state[f"upload_{i}_video"] = vid

    check_result = st.session_state.get("upload_check_result")

    if check_result is None:
        st.info(t("upload_start", L))

    elif not check_result["compatible"]:
        st.error(f"❌  {t('not_compatible', L)}")
        for issue in check_result["issues"]:
            st.write(f"- {issue}")

    else:
        matched_name = check_result.get("matched_template_name")
        detected_club = check_result.get("matched_club", club)
        detected_lang = check_result.get("matched_language", lang)

        # Switch theme if detected club differs from sidebar selection
        if detected_club and detected_club != club:
            _apply_theme(detected_club)
            _render_header(detected_club, detected_lang)

        if matched_name and matched_name in TEMPLATES:
            st.success(f"✅  {t('detected', L)}: **{matched_name}** ({detected_club}, {detected_lang})")
            template_cfg = get_template_config(matched_name, detected_club, detected_lang)
        else:
            st.success(f"✅  {t('compatible', L)}")
            st.warning(t("select_manually", L))
            matched_name = st.selectbox(f"{t('position', L)}:", list(TEMPLATES.keys()), key="upload_tmpl_fallback")
            template_cfg = get_template_config(matched_name, club, lang)

        st.caption(
            f"Slide {check_result['slide_idx']+1} · {check_result['row_count']} rows · "
            f"{check_result['star_count']} stars · "
            f"Rating {'found ✓' if check_result['has_rating_placeholder'] else 'not found ✗'}"
        )

        # ── Player info section for Upload & Edit (read-only, no search) ─────
        st.markdown("---")
        upload_player_data = st.session_state.get(UPLOAD_PDATA_KEY)
        if upload_player_data:
            _render_player_card(
                upload_player_data, editable=True,
                key_prefix="upload_sci_card", state_key=UPLOAD_PDATA_KEY,
            )
            _up_pname = upload_player_data.get("name", "")
            _up_pclub = upload_player_data.get("club", "")
            if _up_pname:
                tm_stats = st.session_state.get(UPLOAD_TM_KEY)
                if tm_stats:
                    _render_stats_card(
                        tm_stats, _up_pname, editable=True,
                        key_prefix="upload_tm_card", state_key=UPLOAD_TM_KEY,
                    )

        # ── Player photo ──────────────────────────────────────────────
        _up_photo_full, _up_photo_circ = _player_photo_section(state_key="upload_player_photo")

        st.markdown("---")
        st.subheader(t("adjust_competencies", L))

        _comp_descs_upload = extract_competency_descriptions(template_cfg)
        star_values, comments, video_data = competency_sections(
            template_cfg["variables"],
            key_prefix="upload",
            defaults_stars=check_result.get("current_star_values", []),
            defaults_comments=check_result.get("current_comments", []),
            defaults_videos=check_result.get("current_videos", []),
            comp_descriptions=_comp_descs_upload,
            template_name=matched_name,
        )

        st.markdown("---")
        col_save, col_gen, col_share = st.columns(3)
        with col_save:
            if st.button(f"{t('save_draft', L)}", use_container_width=True, key="upload_save"):
                s, c, v = _collect_editor_state("upload", len(template_cfg["variables"]))
                # Generate updated PPTX snapshot for the draft
                with st.spinner(t("filling", L)):
                    _snap = fill_from_bytes(
                        st.session_state["upload_bytes"], template_cfg, s, c, v,
                        player_data=st.session_state.get(UPLOAD_PDATA_KEY),
                        tm_stats=st.session_state.get(UPLOAD_TM_KEY),
                        player_photo=st.session_state.get("upload_player_photo_full"),
                        player_photo_circular=st.session_state.get("upload_player_photo_circ"),
                    )
                _snap_bytes = _snap.getvalue()
                rid = storage.save_draft(
                    username,
                    st.session_state.get("upload_active_report_id"),
                    matched_name or "Unknown", detected_club, detected_lang, s, c, v,
                    source="upload",
                    upload_bytes=_snap_bytes,
                    upload_filename=st.session_state.get("upload_filename"),
                    player_data=st.session_state.get(UPLOAD_PDATA_KEY),
                    tm_stats=st.session_state.get(UPLOAD_TM_KEY),
                    photo_full=st.session_state.get("upload_player_photo_full"),
                    photo_circular=st.session_state.get("upload_player_photo_circ"),
                )
                st.session_state["upload_active_report_id"] = rid
                st.success(f"{t('draft_saved', L)} (ID: {rid[:8]})")

        with col_gen:
            if st.button(f"{t('generate_pptx', L)}", type="primary", use_container_width=True, key="upload_gen"):
                s, c, v = _collect_editor_state("upload", len(template_cfg["variables"]))
                with st.spinner(t("filling", L)):
                    output = fill_from_bytes(
                        st.session_state["upload_bytes"], template_cfg, s, c, v,
                        player_data=st.session_state.get(UPLOAD_PDATA_KEY),
                        tm_stats=st.session_state.get(UPLOAD_TM_KEY),
                        player_photo=st.session_state.get("upload_player_photo_full"),
                        player_photo_circular=st.session_state.get("upload_player_photo_circ"),
                    )
                pptx_bytes = output.getvalue()
                pos = matched_name or "Unknown"

                rid = st.session_state.get("upload_active_report_id") or storage.save_draft(
                    username, None, pos, detected_club, detected_lang, s, c, v,
                    source="upload",
                    upload_bytes=st.session_state.get("upload_bytes"),
                    upload_filename=st.session_state.get("upload_filename"),
                    player_data=st.session_state.get(UPLOAD_PDATA_KEY),
                )
                storage.save_finished(username, rid, pos, detected_club, detected_lang, pptx_bytes,
                                      player_name=_current_player_name(UPLOAD_PDATA_KEY),
                                      player_data=st.session_state.get(UPLOAD_PDATA_KEY),
                                      star_values=s, comments=c, video_data=v,
                                      tm_stats=st.session_state.get(UPLOAD_TM_KEY),
                                      photo_full=st.session_state.get("upload_player_photo_full"),
                                      photo_circular=st.session_state.get("upload_player_photo_circ"))
                st.session_state.pop("upload_active_report_id", None)

                st.success(t("done", L))
                st.download_button(
                    f"📥  {t('download_filled', L)}", data=pptx_bytes,
                    file_name=_pptx_filename(pos, UPLOAD_PDATA_KEY),
                    mime="application/vnd.openxmlformats-officedocument.presentationml.presentation",
                    use_container_width=True,
                )

        with col_share:
            if st.button(f"{t('share', L)}", use_container_width=True, key="upload_share"):
                st.session_state["_share_pending"] = "upload"

        # ── Share dialog ────────────────────────────────────────────────────
        if st.session_state.get("_share_pending") == "upload":
            all_users = _get_all_users()
            other_scouts = [u for u in all_users if u != username]
            if not other_scouts:
                st.warning("No other scouts available.")
                st.session_state.pop("_share_pending", None)
            else:
                sel_scout = st.selectbox(t("select_scout", L), other_scouts, key="upload_share_scout")
                c_send, c_cancel = st.columns(2)
                with c_send:
                    if st.button(t("send_report", L), type="primary", use_container_width=True, key="upload_share_send"):
                        s, c, v = _collect_editor_state("upload", len(template_cfg["variables"]))
                        with st.spinner(t("filling", L)):
                            output = fill_from_bytes(
                                st.session_state["upload_bytes"], template_cfg, s, c, v,
                                player_data=st.session_state.get(UPLOAD_PDATA_KEY),
                                tm_stats=st.session_state.get(UPLOAD_TM_KEY),
                                player_photo=st.session_state.get("upload_player_photo_full"),
                                player_photo_circular=st.session_state.get("upload_player_photo_circ"),
                            )
                        pptx_bytes = output.getvalue()
                        pos = matched_name or "Unknown"
                        rid = st.session_state.get("upload_active_report_id") or uuid.uuid4().hex[:12]
                        player = _current_player_name(UPLOAD_PDATA_KEY) or pos
                        storage.share_report(
                            from_username=username,
                            to_username=sel_scout,
                            report_id=rid,
                            position=pos,
                            club=detected_club,
                            language=detected_lang,
                            pptx_bytes=pptx_bytes,
                            player_name=_current_player_name(UPLOAD_PDATA_KEY),
                            star_values=s,
                            comments=c,
                            video_data=v,
                            player_data=st.session_state.get(UPLOAD_PDATA_KEY),
                            tm_stats=st.session_state.get(UPLOAD_TM_KEY),
                            photo_full=st.session_state.get("upload_player_photo_full"),
                            photo_circular=st.session_state.get("upload_player_photo_circ"),
                        )
                        # Also save as finished + mark shared
                        storage.save_finished(username, rid, pos, detected_club, detected_lang, pptx_bytes,
                                              player_name=_current_player_name(UPLOAD_PDATA_KEY),
                                              player_data=st.session_state.get(UPLOAD_PDATA_KEY),
                                              star_values=s,
                                              comments=c,
                                              video_data=v,
                                              tm_stats=st.session_state.get(UPLOAD_TM_KEY),
                                              photo_full=st.session_state.get("upload_player_photo_full"),
                                              photo_circular=st.session_state.get("upload_player_photo_circ"))
                        storage.mark_shared(username, rid, sel_scout)
                        st.session_state.pop("_share_pending", None)
                        # Auto-send notification emails (receiver gets platform link)
                        try:
                            from email_utils import send_share_emails
                            sender_email = all_users.get(username, {}).get("email", "")
                            receiver_email = all_users.get(sel_scout, {}).get("email", "")
                            mail_results = send_share_emails(
                                sender_name=username,
                                sender_email=sender_email,
                                receiver_name=sel_scout,
                                receiver_email=receiver_email,
                                player_name=player,
                            )
                            for side, (ok, err) in mail_results.items():
                                if not ok and err and "no " not in err:
                                    st.warning(f"Email to {side} not sent: {err}")
                        except Exception as exc:
                            st.warning(f"Email sending failed: {exc}")
                        st.success(t("report_shared", L).format(name=sel_scout))
                with c_cancel:
                    if st.button("Cancel", use_container_width=True, key="upload_share_cancel"):
                        st.session_state.pop("_share_pending", None)
                        st.rerun()
