[server]
maxUploadSize = 500
maxMessageSize = 500

[theme]
primaryColor        = "#1a3370"
backgroundColor     = "#f5f7fa"
secondaryBackgroundColor = "#ffffff"
textColor           = "#1a1a2e"
font                = "sans serif"